import { AppProps } from 'next/app';
import Head from 'next/head';
import { ThemeProvider, Global } from '@emotion/react';
import globalStyles, { THEME } from '@/styles/global-styles';
import Layout from '@/components/layout/layout';

export default function App(props: AppProps) {
  const { Component, pageProps } = props;

  return (
    <ThemeProvider theme={THEME}>
      <Head>
        <title>Lunarweb</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Global styles={globalStyles} />
      <Layout>
        <Component {...pageProps} />
      </Layout>
    </ThemeProvider>
  );
}
